# 1. O que o Telegraf vai escutar? (Input)
[[inputs.http_listener_v2]]
  service_address = ":8080"
  paths = ["/arduino"]
  methods = ["POST"]
  data_format = "influx"

# 2. Para onde o Telegraf vai mandar? (Output)
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"